# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'

target 'BSC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BSC

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'BSCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BSC-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BSC-tvOS

  target 'BSC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
